version: '3.8'

services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: hrconnect-sqlserver
    environment:
      SA_PASSWORD: YourStrong!Passw0rd
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
    networks:
      - hrconnect-net

networks:
  hrconnect-net:
    driver: bridge
    name: hrconnect-net
